spring:
  activemq:
    broker-url: tcp://127.0.0.1:11166
    user: jmh
    password: 123456

  mail:
    host: smtp.qq.com
    username: 766213435@qq.com
    password: ytltvktchhyybbdh
    enable: true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true

my_queue: my_queue

server:
  port: 8090